// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace LinkHide.Entities
{
    public partial class HiddenLink
    {
        public int HiddenLinkId { get; set; }
        public int TokenHash { get; set; }
        public string Token { get; set; }
        public int LinkType { get; set; }
        public string Link { get; set; }
        public int Visits { get; set; }
        public int Success { get; set; }
    }
}