// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Wicked.Favorites
{
    public partial class Favorite
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public string LogoUrl { get; set; }
        public string ImageUrl { get; set; }
        public string Url { get; set; }
        public int Votes { get; set; }
        public DateTime? CreatedOn { get; set; }

        public virtual Category Category { get; set; }
    }
}