apiVersion: apps/v1
kind: Deployment
metadata:
  name: deckofcards-deployment
  labels:
    app: deckofcards
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deckofcards
  template:
    metadata:
      labels:
        app: deckofcards
    spec:
      containers:
      - image: deckofcardsbook.azurecr.io/deckofcards
        name: deckofcardsweb
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: deckofcards-dev
  name: deckofcardsweb
spec:
  loadBalancerIP: 52.247.73.250
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: deckofcards
